[package]
name = "code_runner"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.3"
serde = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
lazy_static = "1.4"